apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paper-bookmark

metadata:
  labels:
    app.kubernetes.io/name: paper-bookmark
    app.kubernetes.io/managed-by: argocd

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: paper-bookmark
  app.kubernetes.io/part-of: paper-bookmark

images:
  - name: ghcr.io/s3nthilg0pal/paper-bookmark
    newName: ghcr.io/s3nthilg0pal/paper-bookmark
    newTag: main
